// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlkHrvzA0yw9xGd7Mv6Povu5LkpA98YIk',
    appId: '1:378269547683:web:33a8c67c3f2803b4111316',
    messagingSenderId: '378269547683',
    projectId: 'uber-clone-12d69',
    authDomain: 'uber-clone-12d69.firebaseapp.com',
    storageBucket: 'uber-clone-12d69.appspot.com',
    measurementId: 'G-4WF3H3XYEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmrriZJrT1xRxbqCpVx_-mPWSuWUvO8o',
    appId: '1:378269547683:android:5e90a7e29af7d43b111316',
    messagingSenderId: '378269547683',
    projectId: 'uber-clone-12d69',
    storageBucket: 'uber-clone-12d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPC53zTu3XkoFLeRVjwZlojT7Zd7kGq54',
    appId: '1:378269547683:ios:b2b57f2b7367dd3e111316',
    messagingSenderId: '378269547683',
    projectId: 'uber-clone-12d69',
    storageBucket: 'uber-clone-12d69.appspot.com',
    iosBundleId: 'com.example.uber',
  );
}
